const AUTHENTICATE_ROUTE = {
    LOGIN: '@AUTHENTICATE_ROUTE/LOGIN',
    REGISTER: '@AUTHENTICATE_ROUTE/REGISTER',
    FORGOTPASS: '@AUTHENTICATE_ROUTE/FORGOTPASS',
    SENDOTP: '@AUTHENTICATE_ROUTE/SENDOTP',
    CHANGEPASS: '@AUTHENTICATE_ROUTE/CHANGEPASS',
};

const APP_ROUTE = {
    MAIN_TAB: 'MAIN_TAB',
};

const HOME_ROUTE = {
    ROOT: 'HOME_ROOT',
    HOME: 'HOME',
};

const SEARCH_ROUTE = {
    ROOT: 'SEARCH_ROOT',
    SEARCH: 'SEARCH',
};

const MY_STORY = {
    ROOT: 'MY_STORY_ROOT',
    MY_STORY: 'MY_STORY',
}

const PROFILE_ROUTE = {
    ROOT: 'PROFILE_ROOT',
    PROFILE: 'PROFILE',
}

const TAB_NAVIGATION_ROOT = {
    HOME_ROUTE,
    SEARCH_ROUTE,
    MY_STORY,
    PROFILE_ROUTE,
};

export { APP_ROUTE, TAB_NAVIGATION_ROOT, AUTHENTICATE_ROUTE };
